FROM node:20-alpine AS builder

WORKDIR /app

# 👇 Build args define karo
ARG VITE_NODE_ENV
ARG VITE_PROD_RAZORPAY_SUPER_KEY
ARG VITE_DEV_RAZORPAY_SUPER_KEY
ARG VITE_LOCAL_RAZORPAY_SUPER_KEY
ARG VITE_PROD_BASE_URL
ARG VITE_DEV_BASE_URL
ARG VITE_LOCAL_BASE_URL

# 👇 ENV me convert karo (Vite ko yahi chahiye)
ENV VITE_NODE_ENV=$VITE_NODE_ENV
ENV VITE_PROD_RAZORPAY_SUPER_KEY=$VITE_PROD_RAZORPAY_SUPER_KEY
ENV VITE_DEV_RAZORPAY_SUPER_KEY=$VITE_DEV_RAZORPAY_SUPER_KEY
ENV VITE_LOCAL_RAZORPAY_SUPER_KEY=$VITE_LOCAL_RAZORPAY_SUPER_KEY
ENV VITE_PROD_BASE_URL=$VITE_PROD_BASE_URL
ENV VITE_DEV_BASE_URL=$VITE_DEV_BASE_URL
ENV VITE_LOCAL_BASE_URL=$VITE_LOCAL_BASE_URL

COPY package*.json ./
RUN npm install --legacy-peer-deps --include=dev

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
