
const apiName = {
  adminLogin: 'user/login',
  parentLogin: 'user/parent/login',
  getClassList: 'class/getAll',
  getClassById: 'class/get',
  subject: 'subjects',
  getFeeList: 'fee/feetypes/getAll',
  getFeeStructure: 'fee/feestructure/getAll',
  getFeeStructureByStudentId:'student/feeProfile',
  addFeeStructure: 'fee/feestructure/add',
  updateFeeStructure: 'fee/feestructure/update',
  deleteFeeStructure: 'fee/feestructure/delete',
  getLastAdmissionNumber:'student/getLastAdmissionNumber',
  getStudent: 'student/getStudents',
  getStudentById: 'student/getStudent',
  getFeeByStudentId:'student/feeProfile',
  exams:'/exam-names',
  addSchedule:'/exam-schedules/',
  updateStudent: 'student/updateStudent',
  deleteStudent: 'student/deleteStudent',
  addStudent: 'student/addStudent',
  assignSubject: 'subject-class-mappings',
  addFee: 'fee/feetypes/add',
  deleteFee: 'fee/feetypes/delete',
  updateFee: 'fee/feetypes/update',
  addClass: 'class/add',
  updateClass: 'class/update',
  deleteClass: 'class/delete',
  getSubjectByClass:'subject-class-mappings',
  getStudentByExam:'student/byClassOrSection',
  getStudentFeeByClass:'student/fees/byClassOrSection',
  admitCardByClass:'admitcard/by-class-and-exam',
  collectFee:'payment/collect-fee',
  getPaymentById:'payment/get',
  bulkUpload:'student/bulkAddStudents',
  getProfile:'tenant/',
  uploadCard:'admrec/upload',
};
export default apiName;