name: Deploy Next.js to DigitalOcean

on:
  push:
    branches:
      - manish_front

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 64.227.169.28 >> ~/.ssh/known_hosts

      - name: Upload Build to DigitalOcean
        run: rsync -avz --exclude='node_modules' .next public package.json package-lock.json root@64.227.169.28:/var/www/nextjs-app

      - name: Install Production Dependencies & Restart App
        run: ssh root@64.227.169.28 "bash ~/deploy.sh"
